### ISSUE TITLE
Provide ability to select workers for aerospike cluster

### ISSUE THREAD

**Issue by vasilievip** [aerospike/aerospike-kubernetes-operator#11]
There is 2 options:

nodeSelector 
```
  nodeSelector:
    node-type: standard
```

nodeAffinity
```
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: node-type
            operator: In
            values:
            - standard
```
