### ISSUE TITLE
Broken links to binaries

### ISSUE THREAD

**Issue by vasilievip** [aerospike/aerospike-kubernetes-operator#12]
Not sure if this related to operator or AS docker image itself..

If you ssh to container:
```
root@aerocluster-0:/# find / -name aql
/usr/bin/aql
root@aerocluster-0:/# find / -name asadm
/usr/bin/asadm
root@aerocluster-0:/# find / -name asbackup
/usr/bin/asbackup
```

If you try to run **ls** over folders:
```
root@aerocluster-0:/# ls -l /usr/bin/aql
lrwxrwxrwx 1 root root 22 Aug  9  2019 /usr/bin/aql -> /opt/aerospike/bin/aql
root@aerocluster-0:/# ls -l /usr/bin/asadm
lrwxrwxrwx 1 root root 24 Aug  9  2019 /usr/bin/asadm -> /opt/aerospike/bin/asadm
root@aerocluster-0:/# ls -l /usr/bin/asbackup
lrwxrwxrwx 1 root root 27 Aug  9  2019 /usr/bin/asbackup -> /opt/aerospike/bin/asbackup
```

But folders are missing:

```
root@aerocluster-0:/# ls -l /opt/aerospike/bin
root@aerocluster-0:/# ls -l /opt/aerospike/bin
ls: cannot access '/opt/aerospike/bin': No such file or directory
root@aerocluster-0:/# ls -l /opt/aerospike
total 4
drwxr-xr-x 2 aerospike aerospike 4096 Aug  5 15:12 data
drwxr-xr-x 2 root      root         0 Aug  5 15:12 smd
drwxr-xr-x 3 root      root         0 Aug  3 15:56 usr
drwxr-xr-x 2 root      root         0 Aug  3 15:56 xdr
```

So links are broken or binaries are missing

**Comment by spkesan** [comment]
Hi @vasilievip 

Thanks for reporting this.

The docker image `aerospike/aerospike-server-enterprise` does contain the binaries for tools like `aql`, `asadm`, `asbackup` .... The binaries are placed in `/opt/aerospike/bin/` and a symbolic link is created for each of them in `/usr/bin/`.

I believe you have used the [default example CRs provided](https://github.com/aerospike/aerospike-kubernetes-operator/tree/master/deploy/samples) in this repo as it is.

In the example CR definitions, we are mounting a volume at `/opt/aerospike/` (See https://github.com/aerospike/aerospike-kubernetes-operator/blob/master/deploy/samples/dim_nostorage_cluster_cr.yaml#L12-L17) which overrides the already existing contents in `/opt/aerospike/` that were part of the original docker image. So those `aql`, `asadm`, `asbackup` binaries and other pre-existing files are now hidden.

We will fix it.

At the moment, you can workaround it by configuring a different `work-directory` (see `storage.volumes[0].path` and `aerospikeConfig.service.work-directory`)

```
apiVersion: aerospike.com/v1alpha1
kind: AerospikeCluster
.......

spec:
  size: 3
  build: aerospike/aerospike-server-enterprise:5.0.0.4
  multiPodPerHost: true

  storage:
    volumes:
      - path: /workdir
        storageClass: ssd
        volumeMode: filesystem
        sizeInGB: 3

.......

  aerospikeConfig:
    service:
      feature-key-file: /etc/aerospike/secret/features.conf
      work-directory: /workdir

........
```

Or, you can simply remove the volume for work directory `/opt/aerospike/` from the CR spec and set `validationPolicy.skipWorkDirValidate` to `true`. If you want to persist contents of `/opt/aerospike/data`, `/opt/aerospike/smd`, or `/opt/aerospike/xdr` ... , you can mount volumes for each path separately.

For example,

```
apiVersion: aerospike.com/v1alpha1
kind: AerospikeCluster
......

spec:
  size: 3
  build: aerospike/aerospike-server-enterprise:5.0.0.4
  multiPodPerHost: true

  storage:
    volumes: []

  validationPolicy:
    skipWorkDirValidate: true

.......
```
