### ISSUE TITLE
Currently deployments do not allow new persistent volumes to be added

### ISSUE THREAD

**Issue by antjpar** [aerospike/aerospike-kubernetes-operator#126]
We have a cluster deployed with a single namespace with a persistent volume. We would like to add a second persistent volume and namespace to the deployed cluster.

Currently we get the error message: `admission webhook "vaerospikecluster.kb.io" denied the request: storage config cannot be updated: cannot add persistent volume: {{<nil> <nil> deleteFiles true} delivery {nil nil nil 0xc0005f0480} 0xc000e8cb00 [] []}`

Looking at the code this is not allowed to add storage to a running aerospike cluster.

For us it would make the most sense to add storage and namespaces as we need them as the alternative of either deploying a dedicated cluster or doing an expensive backup, downtime, delete and restore workflow every time we need a new namespace seems not very practical.

Would this be possible? do you also see this as a better way forward?

**Comment by sud82** [comment]
Hi @antjpar, Currently we do not allow adding PV. This is because of a limitation on Statefulset. Statefulset doesn't allow updates in the PV template. 
But your use case can be achieved using the workaround given here https://docs.aerospike.com/cloud/kubernetes/operator/Scaling-namespace-storage

In the future, our plan is to provide a more simple way to achieve these requirements.

**Comment by antjpar** [comment]
Thank you for the link. I tried setting the config as documented but it complains that their is no storage set when I set it on the Rack level

Here is my rack config part which matches the document config
`
 rackConfig:
    namespaces:
      - test
    racks:
      - id: 1
        zone: us-central1-b
        storage:
          filesystemVolumePolicy:
            cascadeDelete: true
            initMethod: deleteFiles
          volumes:
            - name: workdir
              source:
                persistentVolume:
                  storageClass: cephfs
                  volumeMode: Filesystem
                  size: 4Gi
              aerospike:
                path: /opt/aerospike
            - name: aerospike-config-secret
              source:
                secret:
                  secretName: aerospike-secret
              aerospike:
                path: /etc/aerospike/secret
`

the namespace config was is the following:
`
    namespaces:
      - name: test
        memory-size: 4000000000
        replication-factor: 2
        storage-engine:
          data-in-memory: true
          files: [ /opt/aerospike/cephfstest.dat ]
          filesize: 4.294967296e+09
          type: device
`

and this is the error that the operator is giving.
`
 kubectl  apply -f kube/aerospike.yaml 
Error from server (namespace storage file related mountPath /opt/aerospike not found in storage config &{{<nil> <nil> none false} {<nil> <nil> none false} []}): error when creating "kube/aerospike.yaml": admission webhook "vaerospikecluster.kb.io" denied the request: namespace storage file related mountPath /opt/aerospike not found in storage config &{{<nil> <nil> none false} {<nil> <nil> none false} []}

**Comment by antjpar** [comment]
Thank you @tanmayja. It was not clear from the document that the original storage / config should also be in the yaml. 

Below is a full example that upgraded from 1 namespace to 2 namespaces and increased the storage size

Thank you. I am resolving this issue

**Example Yaml**
```
apiVersion: asdb.aerospike.com/v1beta1
kind: AerospikeCluster
metadata:
  name: aerocluster-test
  namespace: aerospike

spec:
  size: 2
  image: aerospike/aerospike-server-enterprise:5.5.0.3

  rackConfig:
    racks:
      - id: 3
        aerospikeConfig:
          namespaces:
            - name: test
              memory-size: 8000000000
              storage-engine:
                data-in-memory: true
                files: [ /opt/aerospike/test.dat ]
                filesize: 8.294967296e+09
                type: device
            - name: test2
              memory-size: 8000000000
              storage-engine:
                data-in-memory: true
                files: [ /opt/aerospike/test2.dat ]
                filesize: 8.294967296e+09
                type: device
        storage:
          filesystemVolumePolicy:
            cascadeDelete: true
            initMethod: deleteFiles
          volumes:
            - name: workdir
              source:
                persistentVolume:
                  storageClass: cephfs
                  volumeMode: Filesystem
                  size: 20Gi
              aerospike:
                path: /opt/aerospike
            - name: aerospike-config-secret
              source:
                secret:
                  secretName: aerospike-secret
              aerospike:
                path: /etc/aerospike/secret

  storage:
    filesystemVolumePolicy:
      cascadeDelete: true
      initMethod: deleteFiles
    volumes:
      - name: workdir
        source:
          persistentVolume:
            storageClass: cephfs
            volumeMode: Filesystem
            size: 4Gi
        aerospike:
          path: /opt/aerospike
      - name: aerospike-config-secret
        source:
          secret:
            secretName: aerospike-secret
        aerospike:
          path: /etc/aerospike/secret
  podSpec:
    multiPodPerHost: true
    aerospikeContainer:
      resources:
        requests:
          memory: 8Gi
          cpu: 2
        limits:
          memory: 12Gi
          cpu: 3

  aerospikeConfig:
    logging:
      - name: /var/log/aerospike/aerospike.log
        any: info
        clustering: debug
      - any: info
        name: console
    service:
      feature-key-file: /etc/aerospike/secret/features.conf

    security:
      enable-security: false

    network:
      service:
        port: 3000
      fabric:
        port: 3001
      heartbeat:
        port: 3002
    namespaces:
      - name: test
        memory-size: 4000000000
        storage-engine:
          data-in-memory: true
          files: [ /opt/aerospike/cephfstest.dat ]
          filesize: 4.294967296e+09
          type: device
```
