### ISSUE TITLE
Unable to create a second cluster on the same node

### ISSUE THREAD

**Issue by ck86** [aerospike/aerospike-kubernetes-operator#181]
The statefulset for the cluster defines the following port configuration for a pod:

```yaml
- containerPort: 3000
  hostPort: 3000
  name: service
  protocol: TCP
```

This opens the port 3000 for the entire node and makes it impossible for the scheduler to spin up another pod on the same node.
