### ISSUE TITLE
Add support for backup operation 

### ISSUE THREAD

**Issue by dorsegal** [aerospike/aerospike-kubernetes-operator#204]
Use cronjob to backup cluster data with option to store it on S3 (or any other cloud) 

example backup script - https://github.com/sysboss/aerospike_backup

Base image with as-tools https://hub.docker.com/r/aerospike/aerospike-tools just need to add aws cli

**Comment by abhishekdwivedi3060** [comment]
Hi @dorsegal, [Aerospike Kubernetes Operator 3.4](https://github.com/aerospike/aerospike-kubernetes-operator/releases/tag/3.4.0) now supports backup and restore.
See the [doc](https://aerospike.com/docs/cloud/kubernetes/operator/backup-and-restore) for more info.

**Comment by ShahroZafar** [comment]
Hi @abhishekdwivedi3060 
I deployed the helm chart aerospike-backup-service service and backup but I dont see deployment of aerospike-backup-service created.

the setup is aerospike-backup-service is deployed in namespace A and the backup CR is deployed in namespace B.


The CR files created are as follows:

aerospikebackupservice
```
apiVersion: asdb.aerospike.com/v1beta1
kind: AerospikeBackupService
metadata:
  labels:
    app: aerospike-backup-service
  name: aerospikebackupservice
  namespace: A
spec:
  config:
    backup-policies:
      test-policy:
        parallel: 3
        remove-files: KeepAll
    service:
      http:
        port: 8080
    storage:
      s3Storage:
        path: 's3://test-bucket'
        s3-endpoint-override: ''
        s3-profile: ''
        s3-region: us-east-1
        type: aws-s3
  image: aerospike/aerospike-backup-service:2.0.0
  resources:
    limits:
      memory: 128Mi
    requests:
      cpu: 100m
      memory: 128Mi
  service:
    type: ClusterIP
```

aerospikebackup
```
apiVersion: asdb.aerospike.com/v1beta1
kind: AerospikeBackup
metadata:
  labels:
    app.kubernetes.io/instance: aerospike-test
  name: aerospiketest
  namespace: B
spec:
  backupService:
    name: aerospikebackupservice
    namespace: A
  config:
    aerospike-cluster:
      B-aerospiketest-aerospike-test:
        label: aerospike-test
        seed-nodes:
          - host-name: aerospike-test.B.svc.cluster.local
            port: 3000
    backup-routines:
      B-aerospiketest-aerospike-test:
        backup-policy: test-policy
        incr-interval-cron: '*/5 * * * * *'
        interval-cron: '@daily'
        namespaces:
          - test
        source-cluster: B-aerospiketest-aerospike-test
        storage: s3Storage

```
