### ISSUE TITLE
not an Aerospike device but not erased

### ISSUE THREAD

**Issue by mateusmuller** [aerospike/aerospike-kubernetes-operator#303]
Hello!

I'm running an AerospikeCluster via Aerospike Operator on top of AWS EKS. For a specific Aerospike namespace, we're using RAW devices to store data.

This has been tested with both EBS and Instance Store volumes. Both throw the same error after the init container initialization:

```
Jul 08 2024 14:40:41 GMT: INFO (drv_ssd): (drv_ssd.c:3514) opened device /dev/xvdf: usable size 74994155520, io-min-size 512
Jul 08 2024 14:40:41 GMT: INFO (drv_ssd): (drv_ssd.c:1067) /dev/xvdf has 8940 wblocks of size 8388608
Jul 08 2024 14:40:41 GMT: CRITICAL (drv_ssd): (drv_ssd.c:2444) /dev/xvdf: not an Aerospike device but not erased - check config or erase device
Jul 08 2024 14:40:41 GMT: WARNING (as): (signal.c:259) SIGUSR1 received, aborting Aerospike Enterprise Edition build 7.1.0.0 os ubuntu22.04 arch x86_64 sha 719892f ee-sha 53fd619
Jul 08 2024 14:40:41 GMT: WARNING (as): (signal.c:293) si_code SI_TKILL (-6)
```

The pod keeps restarting on CrashLoopBackOff state.

I understand we have [this](https://aerospike.com/docs/server/operations/troubleshoot/startup#the-header-has-not-been-zeroized) documentation, but I believe this has to be automated somehow.

I tried adding blkdiscard commands to userdata, but it doesn't work. It only works if I add to a second init container via AerospikeCluster kind:

```yaml
      initContainers:
        # custom container to wipe header 8MiB
        # ref:
        # https://aerospike.com/docs/server/operations/configure/storage/ssd_init
        - name: aerospike-init-custom
          image: aerospike/aerospike-kubernetes-init:2.2.1
          command:
            - sh
            - -c
          args:
            - |
              test ! -f /mnt/tmp/blkdiscard_executed && {
                blkdiscard -v -z --length 8MiB /dev/xvdf
                touch /mnt/tmp/blkdiscard_executed
              } || true
          securityContext:
            privileged: true
```

When this blkdiscard command is executed, then the pod can start properly. I'm pretty sure I shouldn't be doing this to get Aerospike working.

Do you have any recommendations? Shouldn't this initialization be handled by your init container? Or maybe I'm missing something?

Thank you.

**Comment by abhishekdwivedi3060** [comment]
Hi @mateusmuller,
The option you are looking for is `initMethod` in the AerospikeCluster CR. It initialises the volumes attached to the CR. 
For more info, refer: https://aerospike.com/docs/cloud/kubernetes/operator/Cluster-configuration-settings#blockfilesystem-volume-policy

Eg:
```
spec:
  size: 3 
  storage:
    filesystemVolumePolicy:
      initMethod: deleteFiles
      cascadeDelete: true
    blockVolumePolicy:
      cascadeDelete: true
      initMethod: dd
```
