### ISSUE TITLE
Deploying into another namespace

### ISSUE THREAD

**Issue by robbo10** [aerospike/aerospike-kubernetes-operator#60]
Hi folks,

I was following the steps outlined within the [docs ](https://docs.aerospike.com/docs/cloud/kubernetes/operator/Install-the-Operator-on-Kubernetes.html) and have managed to deploy an aerospike cluster with the operator & aerospike cluster pods running within the `aerospike` namespace.

However when I try to deploy a cluster to a different namespace `aerospike-2` for example I can see that the `aerospikeclusters` resource gets created within the namespace, however no pods/replicaset/statefulset ever gets created.

Within the rbac.yml I updated the ClusterRoleBinding to include the below

```

---
# RoleBinding
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: aerospike-cluster
roleRef:
  kind: ClusterRole
  name: aerospike-cluster
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: ServiceAccount
  name: aerospike-cluster
  namespace: aerospike
# # Uncomment below subject entries for deploying clusters in additional namespaces
- kind: ServiceAccount
  name: aerospike-cluster
  namespace: aerospike-2
# - kind: ServiceAccount
#   name: aerospike-cluster
#   namespace: aerospike2

```

There is a serviceaccount called `aerospike-cluster` within the aerospike-2 namespace also.

This is on EKS, k8s version 1.19.

Has anyone any suggestions?

Thanks
