### ISSUE TITLE
Issue when we set more than 1 replicas of operator

### ISSUE THREAD

**Issue by vasilievip** [aerospike/aerospike-kubernetes-operator#7]
Using HA setup described in doc https://github.com/aerospike/aerospike-kubernetes-operator/wiki/Deploy-operator, when we apply the configuration proposed, there is sometimes error reported:
```
"deploy/samples/dim_nostorage_cluster_cr.yaml": Internal error occurred: failed calling webhook "aerospikeclusters.aerospike.com": Post https://aerospike-cluster-webhook.aerospike.svc:443/admission/reviews/aerospikeclusters/mutating?timeout=30s: dial tcp ip:443: connect: connection refused
```
Assumption that this is related to the kubernetes service when it's route traffic to the subscriber pod.
If you retry few times configuration will be eventually applied.

**Comment by sherylsage** [comment]
Hi @vasilievip,
We have tried to reproduce the problem, but have not been able to in our testing with >1 replicas of the operator on GKE and EKS.  If you can provide more details, we will test with your specific configuration.

**Comment by JRaver** [comment]
hello @sherylsage, I will add our configurations, and how to reproduce this situation
The version of our K8S cluster 
```bash
kubectl get no
NAME                       STATUS   ROLES    AGE   VERSION
sandbox-k8s-dp-master-01   Ready    master   13h   v1.19.7
```
Operator specs
```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: aerospike-kubernetes-operator
  namespace: aerospike
spec:
  replicas: 3
  selector:
    matchLabels:
      name: aerospike-kubernetes-operator
  template:
    metadata:
      labels:
        name: aerospike-kubernetes-operator
    spec:
      serviceAccountName: aerospike-kubernetes-operator
      containers:
        - name: aerospike-kubernetes-operator
          image:  docker-hub.artifactory.playticorp.com/aerospike/aerospike-kubernetes-operator:v0.0.12-beta
          command:
          - aerospike-kubernetes-operator
          imagePullPolicy: Always
          ports:
          - containerPort: 8443
          env:
          - name: WATCH_NAMESPACE
            value: aerospike
            # Use below value for watching multiple namespaces by operator
            # value: aerospike,aerospike1,aerospike2
          - name: POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: OPERATOR_NAME
            value: "aerospike-kubernetes-operator"
          - name: LOG_LEVEL
            value: debug
```
When we applied configurations, we often see this situation. Sometimes configuration is successfully applied, but sometimes we have an error.
```bash
root@sandbox-k8s-dp-master-01:/home/eartemenko/aerospike-kubernetes-operator# kubectl apply -f deploy/samples/dim_nostorage_cluster_cr.yaml
Error from server (InternalError): error when creating "deploy/samples/dim_nostorage_cluster_cr.yaml": Internal error occurred: failed calling webhook "aerospikeclusters.aerospike.com": Post "https://aerospike-cluster-webhook.aerospike.svc:443/admission/reviews/aerospikeclusters/mutating?timeout=30s": dial tcp 172.22.221.140:443: connect: connection refused
root@sandbox-k8s-dp-master-01:/home/eartemenko/aerospike-kubernetes-operator# kubectl get po -n aerospike -o wide
NAME                                             READY   STATUS    RESTARTS   AGE   IP              NODE                       NOMINATED NODE   READINESS GATES
aerospike-kubernetes-operator-7c8595d8cb-8cdkk   1/1     Running   0          13m   10.108.10.37    sandbox-k8s-dp-worker-03   <none>           <none>
aerospike-kubernetes-operator-7c8595d8cb-lzg8q   1/1     Running   0          14m   10.108.11.239   sandbox-k8s-dp-worker-01   <none>           <none>
aerospike-kubernetes-operator-7c8595d8cb-mntjr   1/1     Running   0          14m   10.108.10.159   sandbox-k8s-dp-worker-02   <none>           <none>
root@sandbox-k8s-dp-master-01:/home/eartemenko/aerospike-kubernetes-operator# kubectl get svc -n aerospike -o wide
NAME                                    TYPE        CLUSTER-IP       EXTERNAL-IP   PORT(S)             AGE   SELECTOR
aerospike-cluster-webhook               ClusterIP   172.22.221.140   <none>        443/TCP             19m   name=aerospike-kubernetes-operator
aerospike-kubernetes-operator-metrics   ClusterIP   172.22.108.24    <none>        8383/TCP,8686/TCP   17m   name=aerospike-kubernetes-operator
root@sandbox-k8s-dp-master-01:/home/eartemenko/aerospike-kubernetes-operator# kubectl apply -f deploy/samples/dim_nostorage_cluster_cr.yaml
aerospikecluster.aerospike.com/aerocluster created
root@sandbox-k8s-dp-master-01:/home/eartemenko/aerospike-kubernetes-operator# kubectl apply -f deploy/samples/dim_nostorage_cluster_cr.yaml
aerospikecluster.aerospike.com/aerocluster configured
root@sandbox-k8s-dp-master-01:/home/eartemenko/aerospike-kubernetes-operator# kubectl apply -f deploy/samples/dim_nostorage_cluster_cr.yaml
aerospikecluster.aerospike.com/aerocluster configured
root@sandbox-k8s-dp-master-01:/home/eartemenko/aerospike-kubernetes-operator# kubectl apply -f deploy/samples/dim_nostorage_cluster_cr.yaml
Error from server (InternalError): error when applying patch:
{"spec":{"aerospikeConfig":{"logging":[{"any":"info","clustering":"debug","name":"/var/log/aerospike/aerospike.log"}]},"storage":{"volumes":[{"path":"/opt/aerospike","sizeInGB":3,"storageClass":"thin-disk","volumeMode":"filesystem"}]}}}
to:
Resource: "aerospike.com/v1alpha1, Resource=aerospikeclusters", GroupVersionKind: "aerospike.com/v1alpha1, Kind=AerospikeCluster"
Name: "aerocluster", Namespace: "aerospike"
for: "deploy/samples/dim_nostorage_cluster_cr.yaml": Internal error occurred: failed calling webhook "aerospikeclusters.aerospike.com": Post "https://aerospike-cluster-webhook.aerospike.svc:443/admission/reviews/aerospikeclusters/validating?timeout=30s": dial tcp 172.22.221.140:443: connect: connection refused
root@sandbox-k8s-dp-master-01:/home/eartemenko/aerospike-kubernetes-operator# kubectl apply -f deploy/samples/dim_nostorage_cluster_cr.yaml
aerospikecluster.aerospike.com/aerocluster configured
root@sandbox-k8s-dp-master-01:/home/eartemenko/aerospike-kubernetes-operator# kubectl apply -f deploy/samples/dim_nostorage_cluster_cr.yaml
aerospikecluster.aerospike.com/aerocluster configured
root@sandbox-k8s-dp-master-01:/home/eartemenko/aerospike-kubernetes-operator# kubectl apply -f deploy/samples/dim_nostorage_cluster_cr.yaml
aerospikecluster.aerospike.com/aerocluster configured
root@sandbox-k8s-dp-master-01:/home/eartemenko/aerospike-kubernetes-operator# kubectl apply -f deploy/samples/dim_nostorage_cluster_cr.yaml
aerospikecluster.aerospike.com/aerocluster configured
root@sandbox-k8s-dp-master-01:/home/eartemenko/aerospike-kubernetes-operator# sleep 60
root@sandbox-k8s-dp-master-01:/home/eartemenko/aerospike-kubernetes-operator# kubectl apply -f deploy/samples/dim_nostorage_cluster_cr.yaml
aerospikecluster.aerospike.com/aerocluster configured
root@sandbox-k8s-dp-master-01:/home/eartemenko/aerospike-kubernetes-operator# kubectl apply -f deploy/samples/dim_nostorage_cluster_cr.yaml
aerospikecluster.aerospike.com/aerocluster configured
root@sandbox-k8s-dp-master-01:/home/eartemenko/aerospike-kubernetes-operator# kubectl apply -f deploy/samples/dim_nostorage_cluster_cr.yaml
aerospikecluster.aerospike.com/aerocluster configured
root@sandbox-k8s-dp-master-01:/home/eartemenko/aerospike-kubernetes-operator# kubectl apply -f deploy/samples/dim_nostorage_cluster_cr.yaml
aerospikecluster.aerospike.com/aerocluster configured
root@sandbox-k8s-dp-master-01:/home/eartemenko/aerospike-kubernetes-operator# kubectl apply -f deploy/samples/dim_nostorage_cluster_cr.yaml
Error from server (InternalError): error when applying patch:
{"spec":{"aerospikeConfig":{"logging":[{"any":"info","clustering":"debug","name":"/var/log/aerospike/aerospike.log"}]},"storage":{"volumes":[{"path":"/opt/aerospike","sizeInGB":3,"storageClass":"thin-disk","volumeMode":"filesystem"}]}}}
to:
Resource: "aerospike.com/v1alpha1, Resource=aerospikeclusters", GroupVersionKind: "aerospike.com/v1alpha1, Kind=AerospikeCluster"
Name: "aerocluster", Namespace: "aerospike"
for: "deploy/samples/dim_nostorage_cluster_cr.yaml": Internal error occurred: failed calling webhook "aerospikeclusters.aerospike.com": Post "https://aerospike-cluster-webhook.aerospike.svc:443/admission/reviews/aerospikeclusters/mutating?timeout=30s": dial tcp 172.22.221.140:443: connect: connection refused
```

How we reproduce this issue by 100%
1  Delete selector spec in aerospike-cluster-webhook service

```yaml
# Service for webhook
apiVersion: v1
kind: Service
metadata:
  name: aerospike-cluster-webhook
  namespace: aerospike
spec:
  ports:
    - port: 443
      # Can be the name of port 8443 of the container
      targetPort: 8443
```
2) Manually create EP without pod which is master in our case it's pod with IP 10.108.10.37
```bash
kubectl get po -n aerospike  -o wide
NAME                                             READY   STATUS    RESTARTS   AGE    IP              NODE                       NOMINATED NODE   READINESS GATES
aerospike-kubernetes-operator-7c8595d8cb-8cdkk   1/1     Running   0          98m    10.108.10.37    sandbox-k8s-dp-worker-03   <none>           <none>
aerospike-kubernetes-operator-7c8595d8cb-lzg8q   1/1     Running   0          100m   10.108.11.239   sandbox-k8s-dp-worker-01   <none>           <none>
aerospike-kubernetes-operator-7c8595d8cb-mntjr   1/1     Running   0          100m   10.108.10.159   sandbox-k8s-dp-worker-02   <none>           <none>
```

Example of EP spec
```yaml
apiVersion: v1
kind: Endpoints
metadata:
  name: aerospike-cluster-webhook
  namespace: aerospike
subsets:
- addresses:
  - ip: 10.108.10.159
    nodeName: sandbox-k8s-dp-worker-02
    targetRef:
      kind: Pod
      name: aerospike-kubernetes-operator-7c8595d8cb-mntjr
      namespace: aerospike
  - ip: 10.108.11.239
    nodeName: sandbox-k8s-dp-worker-01
    targetRef:
      kind: Pod
      name: aerospike-kubernetes-operator-7c8595d8cb-lzg8q
      namespace: aerospike
  ports:
  - port: 8443
    protocol: TCP
```
3 When you will query EP you will endpoint without primary pod
```bash
kubectl get ep -n aerospike  -o wide aerospike-cluster-webhook
NAME                        ENDPOINTS                               AGE
aerospike-cluster-webhook   10.108.10.159:8443,10.108.11.239:8443   20m
```
And now we always have the error
```bash
root@sandbox-k8s-dp-master-01:/home/eartemenko/aerospike-kubernetes-operator# kubectl apply -f deploy/samples/dim_nostorage_cluster_cr.yaml
Error from server (InternalError): error when applying patch:
{"spec":{"aerospikeConfig":{"logging":[{"any":"info","clustering":"debug","name":"/var/log/aerospike/aerospike.log"}]},"initContainer":"docker-hub.artifactory.playticorp.com/aerospike/aerospike-kubernetes-init:0.0.12","storage":{"volumes":[{"path":"/opt/aerospike","sizeInGB":3,"storageClass":"thin-disk","volumeMode":"filesystem"}]}}}
to:
Resource: "aerospike.com/v1alpha1, Resource=aerospikeclusters", GroupVersionKind: "aerospike.com/v1alpha1, Kind=AerospikeCluster"
Name: "aerocluster", Namespace: "aerospike"
for: "deploy/samples/dim_nostorage_cluster_cr.yaml": Internal error occurred: failed calling webhook "aerospikeclusters.aerospike.com": Post "https://aerospike-cluster-webhook.aerospike.svc:443/admission/reviews/aerospikeclusters/mutating?timeout=30s": dial tcp 172.22.221.140:443: connect: connection refused
root@sandbox-k8s-dp-master-01:/home/eartemenko/aerospike-kubernetes-operator# kubectl apply -f deploy/samples/dim_nostorage_cluster_cr.yaml
Error from server (InternalError): error when applying patch:
{"spec":{"aerospikeConfig":{"logging":[{"any":"info","clustering":"debug","name":"/var/log/aerospike/aerospike.log"}]},"initContainer":"docker-hub.artifactory.playticorp.com/aerospike/aerospike-kubernetes-init:0.0.12","storage":{"volumes":[{"path":"/opt/aerospike","sizeInGB":3,"storageClass":"thin-disk","volumeMode":"filesystem"}]}}}
to:
Resource: "aerospike.com/v1alpha1, Resource=aerospikeclusters", GroupVersionKind: "aerospike.com/v1alpha1, Kind=AerospikeCluster"
Name: "aerocluster", Namespace: "aerospike"
for: "deploy/samples/dim_nostorage_cluster_cr.yaml": Internal error occurred: failed calling webhook "aerospikeclusters.aerospike.com": Post "https://aerospike-cluster-webhook.aerospike.svc:443/admission/reviews/aerospikeclusters/mutating?timeout=30s": dial tcp 172.22.221.140:443: connect: connection refused
root@sandbox-k8s-dp-master-01:/home/eartemenko/aerospike-kubernetes-operator# kubectl apply -f deploy/samples/dim_nostorage_cluster_cr.yaml
Error from server (InternalError): error when applying patch:
{"spec":{"aerospikeConfig":{"logging":[{"any":"info","clustering":"debug","name":"/var/log/aerospike/aerospike.log"}]},"initContainer":"docker-hub.artifactory.playticorp.com/aerospike/aerospike-kubernetes-init:0.0.12","storage":{"volumes":[{"path":"/opt/aerospike","sizeInGB":3,"storageClass":"thin-disk","volumeMode":"filesystem"}]}}}
to:
Resource: "aerospike.com/v1alpha1, Resource=aerospikeclusters", GroupVersionKind: "aerospike.com/v1alpha1, Kind=AerospikeCluster"
Name: "aerocluster", Namespace: "aerospike"
for: "deploy/samples/dim_nostorage_cluster_cr.yaml": Internal error occurred: failed calling webhook "aerospikeclusters.aerospike.com": Post "https://aerospike-cluster-webhook.aerospike.svc:443/admission/reviews/aerospikeclusters/mutating?timeout=30s": dial tcp 172.22.221.140:443: connect: connection refused
root@sandbox-k8s-dp-master-01:/home/eartemenko/aerospike-kubernetes-operator# kubectl apply -f deploy/samples/dim_nostorage_cluster_cr.yaml
Error from server (InternalError): error when applying patch:
{"spec":{"aerospikeConfig":{"logging":[{"any":"info","clustering":"debug","name":"/var/log/aerospike/aerospike.log"}]},"initContainer":"docker-hub.artifactory.playticorp.com/aerospike/aerospike-kubernetes-init:0.0.12","storage":{"volumes":[{"path":"/opt/aerospike","sizeInGB":3,"storageClass":"thin-disk","volumeMode":"filesystem"}]}}}
to:
Resource: "aerospike.com/v1alpha1, Resource=aerospikeclusters", GroupVersionKind: "aerospike.com/v1alpha1, Kind=AerospikeCluster"
Name: "aerocluster", Namespace: "aerospike"
for: "deploy/samples/dim_nostorage_cluster_cr.yaml": Internal error occurred: failed calling webhook "aerospikeclusters.aerospike.com": Post "https://aerospike-cluster-webhook.aerospike.svc:443/admission/reviews/aerospikeclusters/mutating?timeout=30s": dial tcp 172.22.221.140:443: connect: connection refused
```

**Comment by sud82** [comment]
Hi @JRaver, thanks for providing the data. It seems that we have got the problem.

Let me just explain what has been happening here.

If we run multiple operator pods then there will be only a single leader pod, which will have a running webhook server.
Now with the current setup, aerospike-cluster-webhook service points to all the operator pods. Thus, it will send the occasional requests to the non-leader pods, which will obviously fail because there is no webhook server running in the non-leader pod.

This can be fixed if the aerospike-cluster-webhook service points to the leader pod only.
For this, we can add a readiness probe in the operator.yaml file.
Please try the given operator config and let us know if it is working for you.

```yaml
# Operator
apiVersion: apps/v1
kind: Deployment
metadata:
  name: aerospike-kubernetes-operator
  namespace: aerospike
spec:
  replicas: 1
  selector:
    matchLabels:
      name: aerospike-kubernetes-operator
  template:
    metadata:
      labels:
        name: aerospike-kubernetes-operator
    spec:
      serviceAccountName: aerospike-kubernetes-operator
      containers:
        - name: aerospike-kubernetes-operator
          image: aerospike/aerospike-kubernetes-operator:1.0.0
          command:
          - aerospike-kubernetes-operator
          imagePullPolicy: Always
          ports:
          - containerPort: 8443
          env:
          - name: WATCH_NAMESPACE
            value: aerospike
            # Use below value for watching multiple namespaces by operator
            # value: aerospike,aerospike1,aerospike2
          - name: POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: OPERATOR_NAME
            value: "aerospike-kubernetes-operator"
          - name: LOG_LEVEL
            value: debug
          readinessProbe:
            exec:
              command:
              - stat
              - "/tmp/cert"
            initialDelaySeconds: 5
            periodSeconds: 5
            timeoutSeconds: 5
            failureThreshold: 1
```

**Comment by JRaver** [comment]
@sud82  Hello thank you for the response.  I have tested your proposal for HA, it's work I even tested disaster when the leader goes down and can't spin up, and it chooses a new leader. But I think it's not a production-ready solution because, we can't update this operator with the Rolling Update strategy. Now I will explain why
For example, we created deployment from spec with 3 pods
```sh
NAME                                             READY   STATUS    RESTARTS   AGE   IP              NODE                            NOMINATED NODE   READINESS GATES
aerospike-kubernetes-operator-754dc8c66f-27vbk   0/1     Running   0          11s   10.108.85.206   sandbox-b-k8s-stage-worker-01   <none>           <none>
aerospike-kubernetes-operator-754dc8c66f-8w22x   1/1     Running   0          11s   10.108.85.9     sandbox-b-k8s-stage-worker-03   <none>           <none>
aerospike-kubernetes-operator-754dc8c66f-lhzw4   0/1     Running   0          11s   10.108.85.73    sandbox-b-k8s-stage-worker-02   <none>           <none>
```

After that we decide to update it, I just add a new Env variable TEST to the spec.

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: aerospike-kubernetes-operator
  namespace: aerospike
spec:
  replicas: 3
  selector:
    matchLabels:
      name: aerospike-kubernetes-operator
  template:
    metadata:
      labels:
        name: aerospike-kubernetes-operator
    spec:
      serviceAccountName: aerospike-kubernetes-operator
      containers:
        - name: aerospike-kubernetes-operator
          image: docker-hub.artifactory.playticorp.com/aerospike/aerospike-kubernetes-operator:1.0.0
          command:
          - aerospike-kubernetes-operator
          imagePullPolicy: Always
          ports:
          - containerPort: 8443
          env:
          - name: TEST
            value: some_value
          - name: WATCH_NAMESPACE
            value: aerospike
            # Use below value for watching multiple namespaces by operator
            # value: aerospike,aerospike1,aerospike2
          - name: POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: OPERATOR_NAME
            value: "aerospike-kubernetes-operator"
          - name: LOG_LEVEL
            value: debug
          readinessProbe:
            exec:
              command:
              - stat
              - "/tmp/cert"
            initialDelaySeconds: 5
            periodSeconds: 5
            timeoutSeconds: 5
            failureThreshold: 1
```
We applied new spec and now k8s spin up the new pod and stuck

```sh
kubectl get po -n aerospike   -o wide   -w
NAME                                             READY   STATUS    RESTARTS   AGE     IP              NODE                            NOMINATED NODE   READINESS GATES
aerospike-kubernetes-operator-754dc8c66f-27vbk   0/1     Running   0          5m44s   10.108.85.206   sandbox-b-k8s-stage-worker-01   <none>           <none>
aerospike-kubernetes-operator-754dc8c66f-8w22x   1/1     Running   0          5m44s   10.108.85.9     sandbox-b-k8s-stage-worker-03   <none>           <none>
aerospike-kubernetes-operator-754dc8c66f-lhzw4   0/1     Running   0          5m44s   10.108.85.73    sandbox-b-k8s-stage-worker-02   <none>           <none>
aerospike-kubernetes-operator-7f86bfbc74-mncmw   0/1     Running   0          52s     10.108.85.207   sandbox-b-k8s-stage-worker-01   <none>           <none>
kubectl rollout history -n aerospike deploy/aerospike-kubernetes-operator
deployment.apps/aerospike-kubernetes-operator
REVISION  CHANGE-CAUSE
1         <none>
2         <none>

kubectl rollout status -n aerospike deploy/aerospike-kubernetes-operator
Waiting for deployment "aerospike-kubernetes-operator" rollout to finish: 1 out of 3 new replicas have been updated...



^C sleep 100
kubectl rollout status -n aerospike deploy/aerospike-kubernetes-operator
Waiting for deployment "aerospike-kubernetes-operator" rollout to finish: 1 out of 3 new replicas have been updated...
```
Deployment stuck because k8s in the upgrade procedure is waiting  when the pod will be UP and Ready.

If we change the upgrade procedure to Recreate it will redeploy everything,  k8s delete all pods and spin up new, we lost our operator on some small-time, everything will come back, but in rollout status, we will see, not finished deployment
```sh
kubectl rollout history -n aerospike deploy/aerospike-kubernetes-operator
deployment.apps/aerospike-kubernetes-operator
REVISION  CHANGE-CAUSE
1         <none>
2         <none>
3         <none>

kubectl rollout status -n aerospike deploy/aerospike-kubernetes-operator
Waiting for deployment "aerospike-kubernetes-operator" rollout to finish: 1 of 3 updated replicas are available...
^C kubectl get po -n aerospike   -o wide   -w
NAME                                            READY   STATUS    RESTARTS   AGE     IP              NODE                            NOMINATED NODE   READINESS GATES
aerospike-kubernetes-operator-ccb486c7c-fkft6   0/1     Running   0          3m12s   10.108.85.208   sandbox-b-k8s-stage-worker-01   <none>           <none>
aerospike-kubernetes-operator-ccb486c7c-hglfx   1/1     Running   0          3m12s   10.108.85.75    sandbox-b-k8s-stage-worker-02   <none>           <none>
aerospike-kubernetes-operator-ccb486c7c-wn7xv   0/1     Running   0          3m12s   10.108.85.11    sandbox-b-k8s-stage-worker-03   <none>           <none>
```
From my perspective of view, I think you should separate webhooks from the operator and move it to another deployment and after that, you can scale the webhook seperatly
Thank you.
